docker_cimg: &docker_cimg
    working_directory: ~/terraform
    docker:
      - image: cimg/base

myp2_env: &myp2_env
    myp2_env:
      description: "myp2 environment"
      default: "dev"
      type: string


version: 2.1
orbs: 
  terragrunt: dialogue/terragrunt@1.5.2
  aws-cli: circleci/aws-cli@1.3

parameters:
  is_pull_request:
    type: boolean
    default: false
    
  pr_number:
    type: integer
    default: 0

  target_branch:
    type: string
    default: ""


workflows:
#=============================== On Commit Tests ============================
  on-commit-tests:
    unless : 
      or:
        - equal: [ true, << pipeline.parameters.is_pull_request >> ]
    jobs:
      - terragrunt/validate:
          terraform_version: 1.1.7
          terragrunt_version: 0.36.3






