docker_cimg: &docker_cimg
    working_directory: ~/terraform
    docker:
      - image: cimg/base:2021.04

myp2_env: &myp2_env
    myp2_env:
      description: "myp2 environment"
      default: "dev"
      type: string


version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@1.3
  github-cli: circleci/github-cli@2.1.0

parameters:
  is_pull_request:
    type: boolean
    default: false
    
  pr_number:
    type: integer
    default: 0

  target_branch:
    type: string
    default: ""


workflows:
#=============================== On Commit Tests ============================
  on-commit-tests:
    unless : 
      or:
        - equal: [ true, << pipeline.parameters.is_pull_request >> ]
    jobs:
      - validate-tf:
          myp2_env: 'dev'
          context: MYP2

# Jobs
jobs:


  validate-tf:
    parameters:
      <<: *myp2_env
    <<: *docker_cimg
    steps:
      - run:
          name: get-tfenv
          command: git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - run:
          name: setpath-tfenv
          command: echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> $BASH_ENV
      - run:
          name: install-tfenv
          command: tfenv install 1.1.7 && tfenv use 1.1.7
      - run:
          name: install-terragrunt
          command: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.3/terragrunt_linux_amd64 -P ~/tg-binary/ && mv ~/tg-binary/terragrunt_linux_amd64  ~/tg-binary/terragrunt && chmod +x ~/tg-binary/terragrunt && echo 'export PATH="~/tg-binary/:$PATH"' >> $BASH_ENV
      - run:
          name: show-versions
          command: terraform -v &&  ~/terraform/terragrunt -v
      - checkout
      - aws-cli/setup
      - run:
          name: validate-tf
          command: cd ~/terraform/environments/parameters.myp2_env/ && ~/terraform/terragrunt/terragrunt run-all validate

 